[package]
name = "ssh-stage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.3"
anyhow = "1.0.56"
sshkeys = "0.3.2"
